src/Entity/File.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $original_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ext;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="images")
     */
    private $product;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOriginalName(): ?string
    {
        return $this->original_name;
    }

    public function setOriginalName(string $original_name): self
    {
        $this->original_name = $original_name;

        return $this;
    }

    public function getExt(): ?string
    {
        return $this->ext;
    }

    public function setExt(string $ext): self
    {
        $this->ext = $ext;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Controller/Backend/EventController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs;

/**
 * @Route("/backend/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="backend_event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        return $this->render('backend/event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="backend_event_new", methods={"GET","POST"})
     */
    public function new(Request $request, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('backend_event_index');
        }

        return $this->render('backend/event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_event_show", methods={"GET"})
     */
    public function show(Event $event, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        return $this->render('backend/event/show.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="backend_event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('backend_event_index');
        }

        return $this->render('backend/event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_event_index');
    }
}

src/Controller/Backend/FileController.php
<?php

namespace App\Controller\Backend;

use App\Entity\File;
use App\Form\FileType;
use App\Repository\FileRepository;
use mysql_xdevapi\Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Helpers\Common;
use WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs;
use App\Entity\Product;

/**
 * @Route("/backend/file")
 */
class FileController extends AbstractController
{
    /**
     * @Route("/", name="backend_file_index", methods={"GET"})
     */
    public function index(FileRepository $fileRepository, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        return $this->render('backend/file/index.html.twig', [
            'files' => $fileRepository->findAll(),
        ]);
    }

    /**
     * @Route("/audio", name="backend_audio_index", methods={"GET"})
     */
    public function audio(FileRepository $fileRepository, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        return $this->render('backend/file/index.html.twig', [
            'files' => $fileRepository->findBy(['type' => \App\Enum\File::MUSIC_TYPE]),
        ]);
    }

    /**
     * @Route("/video", name="backend_video_index", methods={"GET"})
     */
    public function video(FileRepository $fileRepository, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        return $this->render('backend/file/index.html.twig', [
            'files' => $fileRepository->findBy(['type' => \App\Enum\File::VIDEO_TYPE]),
        ]);
    }

    /**
     * @Route("/photo", name="backend_photo_index", methods={"GET"})
     */
    public function photo(FileRepository $fileRepository, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        return $this->render('backend/file/index.html.twig', [
            'files' => $fileRepository->findBy(['type' => \App\Enum\File::PHOTO_TYPE]),
        ]);
    }

    /**
     * @Route("/new", name="backend_file_new", methods={"GET","POST"})
     */
    public function new(Request $request, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        $model = new File();
        $form = $this->createForm(FileType::class, $model);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $form['file']->getData();
            $ext = $file->guessClientExtension();
            $fileName = Common::getUniqueString() . '.' . $ext;
            try {
                $file->move(
                    $this->getParameter('media_folder'),
                    $fileName
                );
            } catch (FileException $e) {
                throw new \Exception($e);
            }
            $model->setFile($fileName);
            $model->setExt($ext);
            $model->setOriginalName($file->getClientOriginalName());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($model);
            $entityManager->flush();

            return $this->redirectToRoute('backend_index');
        }

        return $this->render('backend/file/new.html.twig', [
            'file' => $model,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_file_show", methods={"GET"})
     */
    public function show(File $file, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        return $this->render('backend/file/show.html.twig', [
            'file' => $file,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="backend_file_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, File $file, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Files", $this->get("router")->generate("backend_file_index"));

        $form = $this->createForm(FileType::class, $file);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('backend_index');
        }

        return $this->render('backend/file/edit.html.twig', [
            'file' => $file,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_file_delete", methods={"DELETE"})
     */
    public function delete(Request $request, File $file): Response
    {
        if ($this->isCsrfTokenValid('delete' . $file->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($file);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_index');
    }


    /**
     * @Route("/product-image-delete/{id}", name="backend_product_image_delete", methods={"DELETE"})
     */
    public function productImageDelete(Request $request, File $file): Response
    {
        $product = $file->getProduct();
        if ($this->isCsrfTokenValid('delete' . $file->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($file);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_product_edit', ['id' => $product->getId()]);
    }

    /**
     * @Route("/product/{id}/add-image", name="backend_file_add_product_image", methods={"GET","POST"})
     */
    public function addProductImage(Request $request, Product $product, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem(
            "Product",
            $this->generateUrl("backend_product_edit", ['id' => $product->getId()])
        );
        $breadcrumbs->addItem(
            "Files",
            $this->generateUrl("backend_file_add_product_image", ['id' => $product->getId()])
        );

        $model = new File();

        $form = $this->createForm(FileType::class, $model);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $form['file']->getData();
            $ext = $file->guessClientExtension();
            $fileName = Common::getUniqueString() . '.' . $ext;
            try {
                $file->move(
                    $this->getParameter('media_folder'),
                    $fileName
                );
            } catch (FileException $e) {
                throw new \Exception($e);
            }
            $model->setType(\App\Enum\File::PRODUCT_IMAGE_TYPE);
            $model->setProduct($product);
            $model->setFile($fileName);
            $model->setExt($ext);
            $model->setOriginalName($file->getClientOriginalName());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($model);
            $entityManager->flush();

            return $this->redirectToRoute('backend_product_edit', ['id' => $product->getId()]);
        }

        return $this->render('backend/file/add-product-image.html.twig', [
            'file' => $model,
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/Backend/IndexController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backend")
 */
class IndexController extends AbstractController
{
    /**
     * @Route("/", name="backend_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('backend/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }
}

src/Controller/Backend/OrderController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs;

/**
 * @Route("/backend/order")
 */
class OrderController extends AbstractController
{
    /**
     * @Route("/", name="backend_order_index", methods={"GET"})
     */
    public function index(OrderRepository $orderRepository, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Orders", $this->get("router")->generate("backend_order_index"));

        return $this->render('backend/order/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_order_show", methods={"GET"})
     */
    public function show(Order $order, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem("Backend", $this->get("router")->generate("backend_index"));
        $breadcrumbs->addItem("Orders", $this->get("router")->generate("backend_order_index"));

        return $this->render('backend/order/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route("/{id}", name="backend_order_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Order $order): Response
    {
        if ($this->isCsrfTokenValid('delete' . $order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_order_index');
    }
}

templates/backend/file/_delete_form.html.twig
<form method="post" action="{{ path('backend_file_delete', {'id': file.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ file.id) }}">
    <button class="btn btn-danger" class="btn btn-primary">Delete</button>
</form>

templates/backend/file/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    {{ form_errors(form) }}
</div>
<div class="form-group">
    {{ form_row(form.title, {'attr': {'class':'form-control'}}) }}
</div>
<div class="form-group">
    {{ form_row(form.content, {'attr': {'class':'form-control'}}) }}
</div>
<div class="form-group">
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/backend/file/add-product-image.html.twig
{% extends 'backend.html.twig' %}

{% block title %}New Product Image{% endblock %}

{% block body %}
    <h1>Create new File</h1>

    {{ form_start(form) }}
    <div class="form-group">
        {{ form_errors(form) }}
    </div>
    <div class="form-group hide">
        {{ form_row(form.description, {'attr': {'disabled':'disabled'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.file, {'attr': {'class':'form-control'}}) }}
    </div>
    <div class="form-group hide">
        {{ form_row(form.type, {'attr': {'disabled':'disabled'}}) }}
    </div>
    <div class="form-group">
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/backend/file/edit.html.twig
{% extends 'backend.html.twig' %}

{% block title %}Edit File{% endblock %}

{% block body %}
    <h1>Edit File</h1>

    {{ form_start(form) }}
    <div class="form-group">
        {{ form_errors(form) }}
    </div>
    <div class="form-group">
        {{ form_row(form.description, {'attr': {'class':'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.type, {'attr': {'class':'form-control'}}) }}
    </div>
    <div class="hide">
        {{ form_row(form.file, {'attr': {'disabled':'disabled'}}) }}
    </div>
    <div class="form-group">
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    </div>
    {{ form_end(form) }}

    <a href="{{ path('backend_index') }}" class="btn btn-primary">back to list</a>

    <div class="pt20">
        {{ include('backend/file/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/backend/file/index.html.twig
{% extends 'backend.html.twig' %}

{% block title %}File index{% endblock %}

{% block body %}
    <h1>File index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Original_name</th>
                <th>Ext</th>
                <th>File</th>
                <th>Description</th>
                <th>Type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for file in files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.originalName }}</td>
                <td>{{ file.ext }}</td>
                <td>{{ file.file }}</td>
                <td>{{ file.description }}</td>
                <td>{{ file.type }}</td>
                <td>
                    <a href="{{ path('backend_file_show', {'id': file.id}) }}" class="btn btn-primary">show</a>
                    <a href="{{ path('backend_file_edit', {'id': file.id}) }}" class="btn btn-primary">edit</a>
                    <div class="list-remove-btn">
                        {{ include('backend/file/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('backend_file_new') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/backend/file/new.html.twig
{% extends 'backend.html.twig' %}

{% block title %}New File{% endblock %}

{% block body %}
    <h1>Create new File</h1>

    {{ form_start(form) }}
    <div class="form-group">
        {{ form_errors(form) }}
    </div>
    <div class="form-group">
        {{ form_row(form.description, {'attr': {'class':'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.file, {'attr': {'class':'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.type, {'attr': {'class':'form-control'}}) }}
    </div>
    <div class="form-group">
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    </div>
    {{ form_end(form) }}


    <a href="{{ path('backend_index') }}" class="btn btn-primary">back to list</a>
{% endblock %}

templates/backend/file/show.html.twig
{% extends 'backend.html.twig' %}

{% block title %}File{% endblock %}

{% block body %}
    <h1>File</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ file.id }}</td>
            </tr>
            <tr>
                <th>Original_name</th>
                <td>{{ file.originalName }}</td>
            </tr>
            <tr>
                <th>Ext</th>
                <td>{{ file.ext }}</td>
            </tr>
            <tr>
                <th>File</th>
                <td>{{ file.file }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ file.description }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ file.type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('backend_index') }}" class="btn btn-primary">back to list</a>

    <a href="{{ path('backend_file_edit', {'id': file.id}) }}" class="btn btn-primary">edit</a>

    <div class="pt20">
        {{ include('backend/file/_delete_form.html.twig') }}
    </div>

{% endblock %}