src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $event_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getEventDate(): ?string
    {
        return $this->event_date;
    }

    public function setEventDate(string $event_date): self
    {
        $this->event_date = $event_date;

        return $this;
    }
}

src/Controller/Frontend/IndexController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\Event;
use App\Entity\File;
use App\Entity\Order;
use App\Entity\Product;
use App\Form\EventType;
use App\Form\FileType;
use App\Form\OrderType;
use App\Helpers\Common;
use App\Repository\EventRepository;
use App\Repository\FileRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Enum\File as FileEnum;
use App\Enum\Product as ProductEnum;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use App\Container\ProductInCart;

/**
 * @Route("/")
 */
class IndexController extends AbstractController
{
    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    /**
     * @Route("/", name="home", methods={"GET"})
     */
    public function home(): Response
    {
        return $this->render('frontend/home.html.twig', []);
    }

    /**
     * @Route("/events", name="events", methods={"GET"})
     */
    public function events(): Response
    {
        $eventRepository = $this->getDoctrine()->getRepository(Event::class);
        $events = $eventRepository->findBy([], ['id' => 'DESC'], 5);

        return $this->render('frontend/events.html.twig', [
            'events' => $events,
        ]);
    }

    /**
     * @Route("/video", name="video", methods={"GET"})
     */
    public function video(): Response
    {
        $fileRepository = $this->getDoctrine()->getRepository(File::class);
        $files = $fileRepository->findBy(['type' => FileEnum::VIDEO_TYPE], ['id' => 'DESC']);

        return $this->render('frontend/video.html.twig', [
            'files' => $files,
        ]);
    }

    /**
     * @Route("/audio", name="audio", methods={"GET"})
     */
    public function audio(): Response
    {
        $fileRepository = $this->getDoctrine()->getRepository(File::class);
        $files = $fileRepository->findBy(['type' => FileEnum::MUSIC_TYPE], ['id' => 'DESC']);

        return $this->render('frontend/audio.html.twig', [
            'files' => $files,
        ]);
    }

    /**
     * @Route("/photo", name="photo", methods={"GET"})
     */
    public function photo(): Response
    {
        $fileRepository = $this->getDoctrine()->getRepository(File::class);
        $files = $fileRepository->findBy(['type' => FileEnum::PHOTO_TYPE], ['id' => 'DESC']);

        return $this->render('frontend/photo.html.twig', [
            'files' => $files,
        ]);
    }

    /**
     * @Route("/products", name="products", methods={"GET"})
     */
    public function products(): Response
    {
        $productRepository = $this->getDoctrine()->getRepository(Product::class);
        $products = $productRepository->findAll();

        return $this->render('frontend/products.html.twig', [
            'products' => $products,
        ]);
    }

    /**
     * @Route("/success-order-page", name="success_order_page", methods={"GET"})
     */
    public function successOrderPage(): Response
    {
        return $this->render('frontend/success_order_page.html.twig', []);
    }

    /**
     * @Route("/cart", name="cart", methods={"GET","POST"})
     */
    public function cart(Request $request, \Swift_Mailer $mailer): Response
    {
        $model = new Order();

        $form = $this->createForm(OrderType::class, $model);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // store order
            $model->setCreatedAt(new \DateTime("now"));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($model);
            $entityManager->flush();

            //send admin email
            $body = "New Order! " . $_ENV['PROTOCOL'] . "://" . $_ENV['DOMAIN'] . "/backend/order/" . $model->getId();
            $message = (new \Swift_Message('Order From ' . $_ENV['DOMAIN']))
                ->setFrom($_ENV['EMAIL_FROM'])
                ->setTo($_ENV['ADMIN_EMAIL'])
                ->setBody($body);
            $mailer->send($message);

            // clear cart
            $this->session->set('cart', null);

            // redirect
            return $this->redirectToRoute('success_order_page');
        }

        $productRepository = $this->getDoctrine()->getRepository(Product::class);
        $cart = $this->session->get('cart');
        $products = [];
        if (!empty($cart)) {
            foreach ($cart as $productInCart) {
                if ($productInCart instanceof ProductInCart) {
                    $product = $productRepository->findOneBy(['id' => $productInCart->getProduct()->getId()]);
                    if ($product instanceof Product) {
                        $productInCart->setProduct($product);
                        $products[] = $productInCart;
                    }
                }
            }
        }

        return $this->render('frontend/cart.html.twig', [
            'products' => $products,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/add-to-cart/{id}", name="add_to_cart", methods={"GET"})
     */
    public function addToCart(Product $product): Response
    {
        $cart = $this->session->get('cart');
        if (empty($cart)) {
            $cart = [];
        }
        if (isset($cart[$product->getId()])) {
            $container = $cart[$product->getId()];
            if ($container instanceof ProductInCart) {
                $container->setQuantity($container->getQuantity() + 1);
            }
        } else {
            $container = new ProductInCart();
            $container->setProduct($product);
            $container->setQuantity(1);
        }
        $cart[$product->getId()] = $container;
        $cart = array_unique($cart);
        $this->session->set('cart', $cart);

        return $this->redirectToRoute('products');
    }

    /**
     * @Route("/remove-from-cart/{id}", name="remove_from_cart", methods={"GET"})
     */
    public function removeFromCart(Product $product): Response
    {
        $cart = $this->session->get('cart');
        if (empty($cart) || empty($cart[$product->getId()])) {
            return $this->redirectToRoute('cart');
        }
        $container = $cart[$product->getId()];
        if ($container instanceof ProductInCart) {
            $currentQuantity = $container->getQuantity();
            if ($currentQuantity < 2) {
                unset($cart[$product->getId()]);
            } else {
                $container->setQuantity($container->getQuantity() - 1);
            }
        }
        $this->session->set('cart', $cart);

        return $this->redirectToRoute('cart');
    }
}

src/Controller/Frontend/SecurityController.php
<?php

namespace App\Controller\Frontend;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \Exception('This method can be blank - it will be intercepted by the logout key on your firewall');
    }
}

templates/frontend/audio.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Audio{% endblock %}

{% block body %}
    <ul>
        {% for file in files %}
            <li>
                <hr>
                <div>
                    {{ file.description }}
                    <br>
                    <br>
                </div>
                <div>
                    <audio controls>
                        <source src="/media/{{ file.file }}" type="audio/{{ file.ext }}">
                    </audio>
                </div>
                <hr>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/frontend/cart.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Cart{% endblock %}

{% block body %}
    <h1>Cart</h1>
    <ul class="products-list">
        {% for item in products %}
            <hr>
            <li>
                {% for image in item.product.images %}
                    <a href="/media/{{ image.file }}" class="image-link">
                        <img data-id="{{ image.id }}" src="/media/{{ image.file }}" alt="">
                    </a>
                {% endfor %}
                <div class="info">
                    <div class="item">
                        <span class="title">Title:</span>
                        <span>{{ item.product.title }}</span>
                    </div>
                    <div class="item">
                        <span class="title">Description:</span>
                        <span>{{ item.product.description }}</span>
                    </div>
                    <div class="item">
                        <span class="title">Price:</span>
                        <span>{{ item.product.price }} (grn)</span>
                    </div>
                    <div class="item">
                        <span class="title">Quantity:</span>
                        <span>{{ item.quantity }}</span>
                    </div>
                </div>
                <a class="btn btn-light add-to-cart-btn"
                   href="{{ path('remove_from_cart', {'id': item.product.id}) }}">Remove</a>
            </li>
            <hr>
        {% endfor %}
    </ul>
    <hr>
    <hr>
    <h3>Create order</h3>
    <div>
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_errors(form) }}
        </div>
        <div class="form-group">
            {{ form_row(form.email, {'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_row(form.name, {'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_row(form.phone, {'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_row(form.skype, {'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_row(form.address, {'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_row(form.comment, {'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            <button class="btn btn-light">{{ button_label|default('Purchase') }}</button>
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('libs/magnific-popup/magnific-popup.css') }}">
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('libs/magnific-popup/jquery.magnific-popup.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.image-link').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                mainClass: 'mfp-img-mobile',
                image: {
                    verticalFit: true
                }
            });
        });
    </script>
{% endblock %}

templates/frontend/events.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Events{% endblock %}

{% block body %}
    <h2>Events</h2>
    {% for event in events %}
        <hr>
        <div>{{ event.eventDate }}</div>
        <div>{{ event.title }}</div>
        <div>{{ event.content }}</div>
        <hr>
    {% endfor %}
{% endblock %}

templates/frontend/header_nav.html.twig
<div class="fl">
    <a href="/"><img class="logo shake-opacity" alt="" src="/images/gurgabs_logo.jpg"></a>
    <a class="btn btn-dark ml50" href="{{ path('home') }}">Home</a>
    <a class="btn btn-dark" href="{{ path('events') }}">Events</a>
    <a class="btn btn-dark" href="{{ path('video') }}">Video</a>
    <a class="btn btn-dark" href="{{ path('audio') }}">Audio</a>
    <a class="btn btn-dark" href="{{ path('photo') }}">Photo</a>
    <a class="btn btn-dark" href="{{ path('products') }}">Merch</a>
    {% if app.user %}
        <a class="btn btn-dark" href="{{ path('backend_index') }}">Admin</a>
        <a class="btn btn-dark" href="{{ path('app_logout') }}">Logout</a></span>
    {% else %}
        <a class="btn btn-dark" href="{{ path('app_login') }}">Login</a></span>
    {% endif %}
</div>
<div class="fr cart-wrap">
    <a href="{{ path('cart') }}">
        <div class="cart">
            <span class="quantity-wrap">
                <span class="quantity">{{ cart_quantity() ?  cart_quantity() : '' }}</span>
            </span>
        </div>
    </a>
</div>
<div class="clear"></div>

templates/frontend/home.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    <div>
        <div class="fl">
            <img src="/images/band.jpg" alt="">
        </div>
        <div class="fl info">
            <div class="item">
                <span class="title">Country of origin:</span>
                <span>Ukraine</span>
            </div>
            <div class="item">
                <span class="title">Location:</span>
                <span>Kharkiv</span>
            </div>
            <div class="item">
                <span class="title">Status:</span>
                <span>Active</span>
            </div>
            <div class="item">
                <span class="title">Formed in:</span>
                <span>1994</span>
            </div>
            <div class="item">
                <span class="title">Genre</span>
                <span>Death Metal</span>
            </div>
            <div class="item">
                <span class="title">Death Metal:</span>
                <span>Ukraine</span>
            </div>
            <div class="item">
                <span class="title">Current label:</span>
                <span>Independent</span>
            </div>
            <div class="item">
                <span class="title">Years active:</span>
                <span>1994 - {{ "now"|date("Y") }}</span>
            </div>
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}

templates/frontend/photo.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Photo{% endblock %}

{% block javascripts %}
    <script src="/js/gallery.js"></script>
{% endblock %}

{% block body %}
    <div id="lightgallery">
        {% for file in files %}
            <a class="gallery-image" href="#">
                <span>{{ file.description }}</span>
                <img data-id="{{ file.id }}" src="/media/{{ file.file }}" alt="">
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/frontend/products.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Products{% endblock %}

{% block body %}
    <ul class="products-list">
        {% for product in products %}
            <hr>
            <li>
                <div id="lightgallery">
                    {% for file in product.images %}
                        <a class="gallery-image" href="#">
                            <span>{{ file.description }}</span>
                            <img data-id="{{ file.id }}" src="/media/{{ file.file }}" alt="">
                        </a>
                    {% endfor %}
                </div>
                <div class="info">
                    <div class="item">
                        <span class="title">Title:</span>
                        <span>{{ product.title }}</span>
                    </div>
                    <div class="item">
                        <span class="title">Description:</span>
                        <span>{{ product.description }}</span>
                    </div>
                    <div class="item">
                        <span class="title">Price:</span>
                        <span>{{ product.price }} (grn)</span>
                    </div>
                </div>
                <a class="btn btn-light add-to-cart-btn"
                   href="{{ path('add_to_cart', {'id': product.id}) }}">Add to cart</a>
            </li>
            <hr>
        {% endfor %}
    </ul>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('libs/magnific-popup/magnific-popup.css') }}">
{% endblock %}

{% block javascripts %}
    <script src="/js/gallery.js"></script>
    <script src="{{ asset('libs/magnific-popup/jquery.magnific-popup.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.image-link').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                mainClass: 'mfp-img-mobile',
                image: {
                    verticalFit: true
                }
            });
        });
    </script>
{% endblock %}

templates/frontend/success_order_page.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Success page{% endblock %}

{% block body %}
    <div class="order-success shake-opacity">
        <h1>Thank you! Your order was created!</h1>
    </div>
{% endblock %}

templates/frontend/video.html.twig
{% extends 'frontend.html.twig' %}

{% block title %}Video{% endblock %}

{% block body %}
    <ul>
        {% for file in files %}
            <li>
                <hr>
                <div>
                    {{ file.description }}
                    <br>
                </div>
                <div>
                    <video width="320" height="240" controls>
                        <source src="/media/{{ file.file }}" type="video/{{ file.ext }}">
                    </video>
                </div>
                <hr>
            </li>
        {% endfor %}
    </ul>
{% endblock %}